# -*- coding: utf-8 -*-
"""Shared pytest fixtures and helpers.

The RSA key below is a THROWAWAY 1024-bit test key that is public on purpose.
It is used only so the suite can produce real PKCS#1 v1.5 signatures with pure
Python (no third-party crypto needed). It has NOTHING to do with the production
signing key, which is generated by tools/gen_keys.py and kept secret.
"""

import base64
import datetime
import hashlib

import pytest

TEST_N = 0xca92e1946e731db8c69f5f5820a3e7e6fafe8eb7c66312bb1e773c92ada6a2204516b75258df2a6b6d603d9c1754b4dc0859d8eeef4ff9fcc00dab7eff95c0eefca1093c9a9f0434b629020692907e0a8801af98ce3914ddc4f792fab9ee9e46a1c757e07b5de3eff23c7c1fc6b81dc85a87f07d42f4f32dee6431f61202fb59
TEST_E = 65537
TEST_D = 0xb5df99d88231a885b50e71b3d5da52e2f68685ec4999b9bf7662e76769b129ee7f191e0e38ec64517f29e126bb6bb9d5b349b7930e1968009d0da8e3a4e4f70a0004484b0f8693c5b493ac85b8219fb7eb9496d97bf2d3648296850a8ab576ac03c421088c92ce02ab821bc86943c37f8a8c7bad132f2d25eafa41a8a5113661

_PREFIX = bytes.fromhex("3031300d060960864801650304020105000420")


def _emsa_pkcs1v15(message, emlen):
    t = _PREFIX + hashlib.sha256(message).digest()
    ps = emlen - len(t) - 3
    if ps < 8:
        raise ValueError("message too long for this key")
    return b"\x00\x01" + (b"\xff" * ps) + b"\x00" + t


def sign_message(message, n=TEST_N, d=TEST_D):
    """Pure-Python PKCS#1 v1.5 SHA-256 signature (test-only signer)."""
    k = (n.bit_length() + 7) // 8
    m = int.from_bytes(_emsa_pkcs1v15(message, k), "big")
    s = pow(m, d, n)
    return s.to_bytes(k, "big")


def make_license(license_id, exp, kid="k1", n=TEST_N, d=TEST_D, sig="auto",
                 version=1):
    """Build a license blob. ``sig='auto'`` signs correctly; pass bytes to fake."""
    message = ("halieum|v=%d|id=%s|exp=%s" % (version, license_id, exp)).encode("utf-8")
    if sig == "auto":
        sig_bytes = sign_message(message, n, d)
    else:
        sig_bytes = sig
    return {
        "v": version,
        "kid": kid,
        "id": license_id,
        "exp": exp,
        "sig": base64.b64encode(sig_bytes).decode("ascii"),
    }


def _exp(delta_days):
    dt = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=delta_days)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


@pytest.fixture
def exp_future():
    return _exp(3650)


@pytest.fixture
def exp_past():
    return _exp(-1)


@pytest.fixture
def signer():
    return sign_message


@pytest.fixture
def license_factory():
    return make_license


@pytest.fixture
def test_pubkey(monkeypatch):
    """Install the throwaway public key so verification can succeed."""
    from halieum import _keys
    monkeypatch.setitem(_keys.PUBKEYS, "k1", (TEST_N, TEST_E))
    monkeypatch.setattr(_keys, "DEFAULT_KID", "k1")
    return (TEST_N, TEST_E)


@pytest.fixture
def isolate_cache(tmp_path, monkeypatch):
    """Redirect the temp cache into the test's tmp dir."""
    directory = tmp_path / "cache"
    directory.mkdir()
    monkeypatch.setenv("HALIEUM_CACHE_DIR", str(directory))
    return str(directory)


@pytest.fixture(autouse=True)
def reset_state():
    """Every test starts from a clean, silent, un-initialized state."""
    import halieum
    from halieum import _log
    halieum._INITIALIZED.clear()
    _log.set_debug(False)
    yield
    halieum._INITIALIZED.clear()
    _log.set_debug(False)
