#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""One-time RSA keypair generator for halieum (development tool).

    pip install pycryptodome
    python tools/gen_keys.py

It will:
  1. Generate a fresh RSA-2048 keypair.
  2. Rewrite ``src/halieum/_keys.py`` so the package embeds the PUBLIC key.
  3. Print the PRIVATE key (PEM) to stdout - copy it into the GitHub Actions
     secret named ``HALIEUM_SIGNING_KEY`` and NEVER commit it.

pycryptodome is required here (and only here / in the signing Action). The
runtime package itself stays standard-library only.
"""

import os
import sys

KEYS_TEMPLATE = '''# -*- coding: utf-8 -*-
"""Embedded RSA *public* keys used to verify license signatures.

AUTO-GENERATED by tools/gen_keys.py - the private counterpart lives only in the
GitHub Actions secret HALIEUM_SIGNING_KEY. Do not edit by hand unless rotating.

Structure: PUBKEYS maps a key id to a tuple (n, e).
"""

DEFAULT_KID = "{kid}"

PUBKEYS = {{
    "{kid}": (
        0x{n_hex},
        {e},
    ),
}}
'''


def main():
    try:
        from Crypto.PublicKey import RSA
    except ImportError:
        sys.stderr.write(
            "pycryptodome is required: pip install pycryptodome\n")
        return 2

    kid = os.environ.get("LIC_KID", "k1") or "k1"
    bits = int(os.environ.get("LIC_KEY_BITS", "2048"))

    key = RSA.generate(bits)
    public = key.publickey()
    n_hex = "%x" % public.n

    here = os.path.dirname(os.path.abspath(__file__))
    keys_path = os.path.normpath(
        os.path.join(here, "..", "src", "halieum", "_keys.py"))

    with open(keys_path, "w", encoding="utf-8") as handle:
        handle.write(KEYS_TEMPLATE.format(kid=kid, n_hex=n_hex, e=public.e))

    sys.stderr.write("[gen_keys] wrote public key -> %s\n" % keys_path)
    sys.stderr.write("[gen_keys] kid=%s bits=%s\n" % (kid, bits))
    sys.stderr.write(
        "\n==== Store this PRIVATE key as GitHub Actions secret "
        "HALIEUM_SIGNING_KEY ====\n")
    # Private key goes to stdout so it can be piped/redirected deliberately.
    sys.stdout.write(key.export_key().decode("utf-8") + "\n")
    sys.stderr.write(
        "==== end private key (never commit it) ====\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
