# -*- coding: utf-8 -*-
"""Embedded RSA *public* keys used to verify license signatures.

AUTO-GENERATED by tools/gen_keys.py - the private counterpart lives only in the
GitHub Actions secret HALIEUM_SIGNING_KEY. Do not edit by hand unless rotating.

Structure: PUBKEYS maps a key id to a tuple (n, e).
"""

DEFAULT_KID = "k1"

PUBKEYS = {
    "k1": (
        0xa8af39522515bd6a9bac2c13fe1e8c880f86ee2669632785c0353a1aa1119bed2f05cbe390aa0c541f31feebcf2fc5331b6d499335367110d3d9ea9abe46769ddae15876a2e36a631dff9289a5a278da6305275454b98dc8ab835a3c3d98310c796ad24f0c30d90df3eeb3e1aea1ae5dd2b0be3cf79640a683756321a4b5b6b9883a1cfda7b49607673b0afe6f01fc3e6858562170944b160d63197e7d888c6ebb147d2da233224b27b6001f0bfae418164a8e3ddff6e6fa99c2fd1ff66b8752c805abf77e04bf0c0b71e4ea0ced9c617a15abf4709c3efd40476e9a378f10b6149676bb09608cacebbbcbd19180a7b01fc73e44989c3dabf6a59f3c0ee7ced7,
        65537,
    ),
}
